services:
  - type: web
    name: 60func
    runtime: node
    buildCommand: cd server && npm install && cd ../client && npm install && npm run build
    startCommand: cd server && node index.js
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NODE_ENV
        value: production
